// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location-service.proto

package location_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail            string   `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Parent               int32    `protobuf:"varint,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Status               int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	MemberId             int64    `protobuf:"varint,7,opt,name=memberId,proto3" json:"memberId,omitempty"`
	DbId                 string   `protobuf:"bytes,8,opt,name=dbId,proto3" json:"dbId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_923754fbfaedd8df, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *User) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *User) GetParent() int32 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetMemberId() int64 {
	if m != nil {
		return m.MemberId
	}
	return 0
}

func (m *User) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

type LocationRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,3,opt,name=long,proto3" json:"long,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	MemberName           string   `protobuf:"bytes,6,opt,name=memberName,proto3" json:"memberName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationRequest) Reset()         { *m = LocationRequest{} }
func (m *LocationRequest) String() string { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()    {}
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_923754fbfaedd8df, []int{1}
}

func (m *LocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationRequest.Unmarshal(m, b)
}
func (m *LocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationRequest.Marshal(b, m, deterministic)
}
func (m *LocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationRequest.Merge(m, src)
}
func (m *LocationRequest) XXX_Size() int {
	return xxx_messageInfo_LocationRequest.Size(m)
}
func (m *LocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationRequest proto.InternalMessageInfo

func (m *LocationRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LocationRequest) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LocationRequest) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *LocationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LocationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *LocationRequest) GetMemberName() string {
	if m != nil {
		return m.MemberName
	}
	return ""
}

type LocationResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationResponse) Reset()         { *m = LocationResponse{} }
func (m *LocationResponse) String() string { return proto.CompactTextString(m) }
func (*LocationResponse) ProtoMessage()    {}
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_923754fbfaedd8df, []int{2}
}

func (m *LocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationResponse.Unmarshal(m, b)
}
func (m *LocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationResponse.Marshal(b, m, deterministic)
}
func (m *LocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationResponse.Merge(m, src)
}
func (m *LocationResponse) XXX_Size() int {
	return xxx_messageInfo_LocationResponse.Size(m)
}
func (m *LocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocationResponse proto.InternalMessageInfo

func (m *LocationResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LocationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LocationResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*LocationRequest)(nil), "LocationRequest")
	proto.RegisterType((*LocationResponse)(nil), "LocationResponse")
}

func init() { proto.RegisterFile("location-service.proto", fileDescriptor_923754fbfaedd8df) }

var fileDescriptor_923754fbfaedd8df = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0xae, 0xd3, 0x30,
	0x14, 0x94, 0xd3, 0x36, 0x6d, 0x1e, 0x52, 0x29, 0x06, 0x55, 0x56, 0x55, 0x55, 0x51, 0x56, 0x15,
	0x12, 0x8d, 0x80, 0x1d, 0x5b, 0xc4, 0xa2, 0x12, 0x62, 0x61, 0xe8, 0x01, 0xdc, 0xe4, 0x29, 0x58,
	0x4a, 0xe2, 0x60, 0xbb, 0x3d, 0x00, 0x57, 0xe0, 0x08, 0xdc, 0x85, 0x0b, 0x70, 0x05, 0x0e, 0x82,
	0xfc, 0xd2, 0xb4, 0x55, 0xf5, 0x77, 0x33, 0xf3, 0x2c, 0xbf, 0x99, 0xb1, 0x61, 0x59, 0x9b, 0x42,
	0x79, 0x6d, 0xda, 0x37, 0x0e, 0xed, 0x59, 0x17, 0xb8, 0xeb, 0xac, 0xf1, 0x66, 0xb5, 0xae, 0x8c,
	0xa9, 0x6a, 0xcc, 0x55, 0xa7, 0x73, 0xd5, 0xb6, 0xc6, 0xd3, 0x21, 0xd7, 0x4f, 0xb3, 0x3f, 0x0c,
	0xc6, 0x07, 0x87, 0x96, 0xcf, 0x21, 0xd2, 0xa5, 0x60, 0x29, 0xdb, 0x8e, 0x64, 0xa4, 0x4b, 0xbe,
	0x82, 0xd9, 0xc9, 0xa1, 0xfd, 0xa2, 0x1a, 0x14, 0x51, 0xca, 0xb6, 0x89, 0xbc, 0x72, 0xbe, 0x86,
	0x24, 0xe0, 0x4f, 0x8d, 0xd2, 0xb5, 0x18, 0xd1, 0xf0, 0x26, 0xf0, 0x57, 0x30, 0xa9, 0xf1, 0x8c,
	0xb5, 0x18, 0xa7, 0x6c, 0x3b, 0x91, 0x3d, 0xe1, 0x4b, 0x88, 0x3b, 0x65, 0xb1, 0xf5, 0x62, 0x42,
	0xf2, 0x85, 0x05, 0xdd, 0x79, 0xe5, 0x4f, 0x4e, 0xc4, 0xbd, 0xde, 0xb3, 0xb0, 0xbf, 0xc1, 0xe6,
	0x88, 0x76, 0x5f, 0x8a, 0x29, 0xb9, 0xba, 0x72, 0xce, 0x61, 0x5c, 0x1e, 0xf7, 0xa5, 0x98, 0xd1,
	0x6a, 0xc2, 0xd9, 0x6f, 0x06, 0xcf, 0x3f, 0x5f, 0x1a, 0x90, 0xf8, 0xe3, 0x84, 0xce, 0xf3, 0x05,
	0x8c, 0x54, 0xa7, 0x29, 0x54, 0x22, 0x03, 0x0c, 0x4a, 0xad, 0x3c, 0x05, 0x62, 0x32, 0xc0, 0x70,
	0x57, 0x6d, 0xda, 0x8a, 0x62, 0x30, 0x49, 0x38, 0x78, 0x0a, 0x71, 0xf6, 0x25, 0x45, 0x48, 0xe4,
	0x85, 0xf1, 0x14, 0x9e, 0x95, 0xe8, 0x0a, 0xab, 0xbb, 0xb0, 0x85, 0x82, 0x24, 0xf2, 0x5e, 0xe2,
	0x1b, 0x80, 0xde, 0x25, 0xf5, 0x16, 0xd3, 0x81, 0x3b, 0x25, 0xfb, 0x06, 0x8b, 0x9b, 0x49, 0xd7,
	0x99, 0xd6, 0xe1, 0x13, 0x2e, 0x05, 0x4c, 0x1b, 0x74, 0x4e, 0x55, 0x43, 0xf5, 0x03, 0x0d, 0xdd,
	0xa2, 0xb5, 0xc6, 0x92, 0xdd, 0x99, 0xec, 0xc9, 0xbb, 0xef, 0xb7, 0xe8, 0x5f, 0xfb, 0xb7, 0xe7,
	0x07, 0x98, 0x7f, 0xb4, 0xa8, 0x3c, 0x0e, 0x03, 0xbe, 0xd8, 0x3d, 0xd4, 0xb3, 0x7a, 0xb1, 0x7b,
	0xf4, 0x92, 0x6d, 0x7e, 0xfe, 0xfd, 0xf7, 0x2b, 0x12, 0xd9, 0xcb, 0xfc, 0xfc, 0x36, 0x1f, 0x3e,
	0x54, 0x5e, 0xd0, 0x4d, 0x1f, 0xd8, 0xeb, 0x63, 0x4c, 0xbf, 0xe6, 0xfd, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0x01, 0xb8, 0xf4, 0x6d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationServiceClient interface {
	CreateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error)
}

type locationServiceClient struct {
	cc *grpc.ClientConn
}

func NewLocationServiceClient(cc *grpc.ClientConn) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) CreateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, "/LocationService/CreateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
type LocationServiceServer interface {
	CreateLocation(context.Context, *LocationRequest) (*LocationResponse, error)
}

// UnimplementedLocationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (*UnimplementedLocationServiceServer) CreateLocation(ctx context.Context, req *LocationRequest) (*LocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLocation not implemented")
}

func RegisterLocationServiceServer(s *grpc.Server, srv LocationServiceServer) {
	s.RegisterService(&_LocationService_serviceDesc, srv)
}

func _LocationService_CreateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).CreateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocationService/CreateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).CreateLocation(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLocation",
			Handler:    _LocationService_CreateLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location-service.proto",
}
